### ISSUE TITLE
Issue retrieving token list from gateway - 504 timed out

### ISSUE THREAD

**Issue by tryingtokeepup** [ethereum-lists/tokens#265]
It seems that the gateway is timing out for me; I'm trying to get the tokens for the Ambo project, but we're having issues hitting the gateway to retrieve the complied token list. Do you have a cached copy available somewhere?

Sorry for this!

**Comment by ligi** [comment]
can you elaborate which gateway you mean?
All token definitions are on github.

**Comment by MicahZoltu** [comment]
I suspect they mean the IPFS gateway, which I'm running into trouble with as well.  The instructions in the readme explain how to get the latest list as generated by the CI server, but it _appears_ that CI is not actually pinning the results so they are falling out of the IPFS global cache due to infrequent usage.
